spring:
  application:
    name: hearify
  datasource:
    url: jdbc:mysql://mysql:3306/hearifydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 5000

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.orm.jpa: DEBUG
